openapi: "3.0.1"
info:
  version: "1.0.0"
  title: "Photo Sharing Service"
  description: "For the photo lover in us all!"
servers:
  - url: "http://localhost:3000/api"
    description: "localhost"
  - url: "https://{domain}/api"
    description: "Production Server"
    variables:
      domain:
        default: localhost:3000
        description: Domain
tags:
  - name: "photo"
    description: "Show off all your best pictures"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
paths:
  /photo:
    get:
      summary: "Fetch a single photo"
      description: "Returns a single picture"
      responses:
        418:
          description: "Photo accepted"
    post:
      summary: "Add a new picture to the store"
      description: ""
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              additionalProperties: false
              type: object
              properties:
                location:
                  type: "string"
                  format: "binary"
                category:
                  type: "string"
                  format: "binary"
              required:
                - category
      responses:
        200:
          description: OK
          content:
            aplication/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      photoRecieved:
                        type: boolean
                    required:
                      - photoRecieved
        405:
          description: "Invalid input"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
