openapi: "3.0.1"
info:
  version: "1.0.0"
  title: "Photo Sharing Service"
servers:
  - url: http://localhost:3000/api
    description: localhost
  - url: https://{domain}/api
    description: Production Server
    variables:
      domain:
        default: localhost:3000
        description: Domain
tags:
  - name: "photo"
    description: "Show off all your best pictures"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
paths:
  /photo:
    get:
      tags:
        - "photo"
      summary: "Find picture by ID"
      description: "Returns a single picture"
      operationId: "getPicturetById"
      produces:
        - "application/json"
      parameters:
        - name: "pictureId"
          in: "path"
          description: "ID of picture to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/picture"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Picture not found"
      security:
        - api_key: []
    post:
      tags:
        - "photo"
      summary: "Add a new picture to the store"
      description: ""
      operationId: "addpicture"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "picture object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/picture"
      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"
      security:
        - picturestore_auth:
            - "write:pictures"
            - "read:pictures"
